/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Clases.*;
import Controlador.*;
import java.io.File;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    DefaultTableModel modelCli;
    DefaultTableModel modelPet;
    DefaultTableModel modelplan;
    CCliente ccliente;
    CCMascota ccmascota;
    CCPlan ccplan;
    CCPago ccpago;

    JFileChooser explorador = new JFileChooser();
    File factura;

    Factura a = new Factura();

    public Vista() {
        initComponents();
        setLocationRelativeTo(null);
        this.ccliente = new CCliente();
        this.ccmascota = new CCMascota();
        this.ccplan = new CCPlan();
        this.ccpago = new CCPago();

        String[] t = {"identificacion", "nombre", "apellido", "location", "telefono"};
        String[] m = {"#", "Codigo", "Mascota", "Fecha", "Peso", "Especie", "CLiente"};
        String[] p = {"#", "Codigo", "Plan", "valor"};
        modelCli = new DefaultTableModel(null, t);
        modelPet = new DefaultTableModel(null, m);
        modelplan = new DefaultTableModel(null, p);
        tbCLientes.setModel(modelCli);
        tbPet.setModel(modelPet);
        tbPlan.setModel(modelplan);

        mostrarClientes();
        mostrarMascotas();
        comboBoxCliente();
        mostrarPlanes();
        comboBoxMascota();
        comboBoxPlan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcc = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        txtAgregarCliente = new javax.swing.JButton();
        BTNEDITAR = new javax.swing.JButton();
        btnConsultarCliente = new javax.swing.JButton();
        btneliminarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCLientes = new javax.swing.JTable();
        btncancelar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtCodigoplan = new javax.swing.JTextField();
        cbNamePlan = new javax.swing.JComboBox<>();
        TxtPrecioPlan = new javax.swing.JTextField();
        btnAgregarPLan = new javax.swing.JButton();
        btnEditarPlan = new javax.swing.JButton();
        btnConsultarPlan = new javax.swing.JButton();
        btnEliminarPlan = new javax.swing.JButton();
        LimpiarPlan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbPlan = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNumeroCuotas = new javax.swing.JTextField();
        cbfechapago = new com.toedter.calendar.JDateChooser();
        cbidMascotapagos = new javax.swing.JComboBox<>();
        cbidplanpagos = new javax.swing.JComboBox<>();
        btnGenerarRecibo = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCOD = new javax.swing.JTextField();
        txtmascotaname = new javax.swing.JTextField();
        txtfechanacimiento = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        cbespecie = new javax.swing.JComboBox<>();
        cbcliente = new javax.swing.JComboBox<>();
        btnCrearmascota = new javax.swing.JButton();
        btnmodificarmascota = new javax.swing.JButton();
        btnconsultarmascota = new javax.swing.JButton();
        btneliminarmascota = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPet = new javax.swing.JTable();
        txtIDpkmascota = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));

        jLabel1.setText("CC");

        jLabel2.setText(" NAME");

        jLabel3.setText("LASTNAME");

        jLabel4.setText("LOCATION");

        jLabel5.setText("PHONE");

        txtAgregarCliente.setText("AGREGAR");
        txtAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarClienteActionPerformed(evt);
            }
        });

        BTNEDITAR.setText("EDITAR");
        BTNEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEDITARActionPerformed(evt);
            }
        });

        btnConsultarCliente.setText("CONSULTAR");
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        btneliminarCliente.setText("ELIMINAR");
        btneliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarClienteActionPerformed(evt);
            }
        });

        tbCLientes.setBackground(new java.awt.Color(204, 255, 204));
        tbCLientes.setFont(new java.awt.Font("SimSun", 0, 12)); // NOI18N
        tbCLientes.setForeground(new java.awt.Color(0, 0, 0));
        tbCLientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbCLientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCLientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCLientes);

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documentos\\NetBeansProjects\\Veterinaria\\src\\main\\java\\Vista\\dueño.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtAgregarCliente)
                                .addGap(29, 29, 29)
                                .addComponent(BTNEDITAR)
                                .addGap(40, 40, 40)
                                .addComponent(btnConsultarCliente)
                                .addGap(38, 38, 38)
                                .addComponent(btneliminarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btncancelar)))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel5))
                                .addComponent(jLabel4)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcc, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtname)
                            .addComponent(txtlastname)
                            .addComponent(txtlocation)
                            .addComponent(txtphone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgregarCliente)
                    .addComponent(BTNEDITAR)
                    .addComponent(btnConsultarCliente)
                    .addComponent(btneliminarCliente)
                    .addComponent(btncancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CLIENTE", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setText("Codigo");

        jLabel14.setText("Plan's Name");

        jLabel15.setText("Price");

        cbNamePlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GOLD", "PREMIUM", "BASIC" }));

        btnAgregarPLan.setText("AGREGAR");
        btnAgregarPLan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPLanActionPerformed(evt);
            }
        });

        btnEditarPlan.setText("Editar");

        btnConsultarPlan.setText("CONSULTAR");

        btnEliminarPlan.setText("ELIMINAR");

        LimpiarPlan.setText("CANCELAR");

        tbPlan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbPlan);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documentos\\NetBeansProjects\\Veterinaria\\src\\main\\java\\Vista\\plan.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAgregarPLan)
                                .addGap(38, 38, 38)
                                .addComponent(btnEditarPlan)
                                .addGap(37, 37, 37)
                                .addComponent(btnConsultarPlan)
                                .addGap(54, 54, 54)
                                .addComponent(btnEliminarPlan)
                                .addGap(31, 31, 31)
                                .addComponent(LimpiarPlan))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbNamePlan, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE)
                            .addComponent(txtCodigoplan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtPrecioPlan))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtCodigoplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cbNamePlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TxtPrecioPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPLan)
                    .addComponent(btnEditarPlan)
                    .addComponent(btnConsultarPlan)
                    .addComponent(btnEliminarPlan)
                    .addComponent(LimpiarPlan))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PLAN", jPanel3);

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));

        jLabel17.setText("FECHA");

        jLabel18.setText("NUMERO DE CUOTAS");

        jLabel19.setText("ID MASCOTA");

        jLabel20.setText("ID PLAN");

        cbidMascotapagos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbidMascotapagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbidMascotapagosActionPerformed(evt);
            }
        });

        cbidplanpagos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGenerarRecibo.setBackground(new java.awt.Color(51, 0, 204));
        btnGenerarRecibo.setText("GENERAR RECIBO");
        btnGenerarRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReciboActionPerformed(evt);
            }
        });

        btnImprimir.setBackground(new java.awt.Color(102, 255, 102));
        btnImprimir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documentos\\NetBeansProjects\\Veterinaria\\src\\main\\java\\Vista\\factura.png")); // NOI18N
        btnImprimir.setText("IMPRIMIR RECIBO");
        btnImprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jButton1.setText("REPORTES FACTURAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel22.setText("FACTURACIÓN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGenerarRecibo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbfechapago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumeroCuotas)
                            .addComponent(cbidMascotapagos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbidplanpagos, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel22)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(cbfechapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtNumeroCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel19))
                    .addComponent(cbidMascotapagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(cbidplanpagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnGenerarRecibo)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PAGO", jPanel4);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel6.setText("COD");

        jLabel7.setText("NAME PET");

        jLabel8.setText("BIRTHDAY ");

        jLabel9.setText("HEIGHT");

        jLabel10.setText("SPECIE");

        jLabel11.setText("CLIENT");

        cbespecie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CANINO", "FELINO", "ANFIBIO", "ARACNIDO" }));

        cbcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbclienteActionPerformed(evt);
            }
        });

        btnCrearmascota.setBackground(new java.awt.Color(0, 0, 255));
        btnCrearmascota.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearmascota.setText("AGREAGAR");
        btnCrearmascota.setActionCommand("AGREGAR");
        btnCrearmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearmascotaActionPerformed(evt);
            }
        });

        btnmodificarmascota.setBackground(new java.awt.Color(0, 0, 255));
        btnmodificarmascota.setForeground(new java.awt.Color(255, 255, 255));
        btnmodificarmascota.setText("EDITAR");
        btnmodificarmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarmascotaActionPerformed(evt);
            }
        });

        btnconsultarmascota.setBackground(new java.awt.Color(0, 0, 255));
        btnconsultarmascota.setForeground(new java.awt.Color(255, 255, 255));
        btnconsultarmascota.setText("CONSULTAR");
        btnconsultarmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarmascotaActionPerformed(evt);
            }
        });

        btneliminarmascota.setBackground(new java.awt.Color(0, 0, 255));
        btneliminarmascota.setForeground(new java.awt.Color(255, 255, 255));
        btneliminarmascota.setText("ELIMINAR");
        btneliminarmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarmascotaActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("CANCELAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        tbPet.setBackground(new java.awt.Color(255, 255, 153));
        tbPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPet);

        txtIDpkmascota.setBackground(new java.awt.Color(102, 255, 102));
        txtIDpkmascota.setBorder(null);
        txtIDpkmascota.setEnabled(false);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\OneDrive\\Documentos\\NetBeansProjects\\Veterinaria\\src\\main\\java\\Vista\\mascota.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtfechanacimiento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmascotaname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCOD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbespecie, javax.swing.GroupLayout.Alignment.LEADING, 0, 193, Short.MAX_VALUE)
                                    .addComponent(txtpeso, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(51, 51, 51)
                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btnCrearmascota)
                                .addGap(44, 44, 44)
                                .addComponent(btnmodificarmascota)
                                .addGap(42, 42, 42)
                                .addComponent(btnconsultarmascota)
                                .addGap(54, 54, 54)
                                .addComponent(btneliminarmascota)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtIDpkmascota, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(cbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIDpkmascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtmascotaname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbespecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearmascota)
                    .addComponent(btnmodificarmascota)
                    .addComponent(btnconsultarmascota)
                    .addComponent(btneliminarmascota)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MASCOTAS", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPetMouseClicked
        if (evt.getClickCount() == 1) {
            JTable recep = (JTable) evt.getSource();

            txtIDpkmascota.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 0).toString());
            txtCOD.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 1).toString());
            txtmascotaname.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 2).toString());
            txtfechanacimiento.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 3).toString());
            txtpeso.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 4).toString());

            cbespecie.setSelectedItem(recep.getModel().getValueAt(recep.getSelectedRow(), 5).toString());

            cbcliente.setSelectedItem(recep.getModel().getValueAt(recep.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_tbPetMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void btneliminarmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarmascotaActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this, "Confirmas la eliminacion de la mascota", null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmacion == 0) {
            String idpk = txtIDpkmascota.getText();

            var rta = ccmascota.borrarMascota(idpk);

            if (rta) {
                JOptionPane.showMessageDialog(this, "MASCOTA eliminado de la bd con exito !");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo borrar el registro !");
            }

            limpiarMasocta();
            mostrarMascotas();

        }
        mostrarMascotas();
    }//GEN-LAST:event_btneliminarmascotaActionPerformed

    private void btnconsultarmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarmascotaActionPerformed

        String codigom = JOptionPane.showInputDialog("Digita el codigo de la mascota a buscar");
        var l = ccmascota.listarMascotas();

        var info = "";

        for (int i = 0; i < l.size(); i++) {
            if (l.get(i).getCodigo().equals(codigom)) {
                info = l.get(i).toString();
                System.out.println(info);
                JOptionPane.showMessageDialog(this, info);
            }

        }
        if (info == "") {
            JOptionPane.showMessageDialog(this, "No se encontro el registro");

        }

    }//GEN-LAST:event_btnconsultarmascotaActionPerformed

    private void btnmodificarmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarmascotaActionPerformed
        try {
            if (validarDatosMascota()) {

                int idPK = Integer.parseInt(txtIDpkmascota.getText());
                String codigo = txtCOD.getText();
                String nombre = txtmascotaname.getText();
                int annioNac = Integer.parseInt(txtfechanacimiento.getText());
                int peso = Integer.parseInt(txtpeso.getText());
                String especie = cbespecie.getSelectedItem().toString();
                String clienteSeleccionado = cbcliente.getSelectedItem().toString();

                int primerEspacio = clienteSeleccionado.indexOf(" ");
                int idFkCliente = Integer.parseInt(clienteSeleccionado.substring(0, primerEspacio));
                System.out.println(idFkCliente);

                Mascota m = new Mascota(codigo, nombre, annioNac, peso, especie, idFkCliente);
                m.setIdPk(idPK);
                if (ccmascota.editarMascota(m) == true) {
                    JOptionPane.showMessageDialog(null, "Editado!");
                } else {
                    JOptionPane.showMessageDialog(null, "OPPS!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "FALTAN DATOS POR INGRESAR!");
            }
            this.comboBoxCliente();
            mostrarMascotas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS MAL DIGITADOS!");
        }
    }//GEN-LAST:event_btnmodificarmascotaActionPerformed

    private void btnCrearmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearmascotaActionPerformed

        try {
            if (validarDatosMascota()) {

                String codigo = txtCOD.getText();
                String nombre = txtmascotaname.getText();
                int annioNac = Integer.parseInt(txtfechanacimiento.getText());
                int peso = Integer.parseInt(txtpeso.getText());
                String especie = cbespecie.getSelectedItem().toString();
                String clienteSeleccionado = cbcliente.getSelectedItem().toString();

                int primerEspacio = clienteSeleccionado.indexOf(" ");
                int idFkCliente = Integer.parseInt(clienteSeleccionado.substring(0, primerEspacio));
                System.out.println(idFkCliente);

                Mascota m = new Mascota(codigo, nombre, annioNac, peso, especie, idFkCliente);
                if (ccmascota.crearMascota(m) == true) {
                    JOptionPane.showMessageDialog(null, "AGREGADO!");
                } else {
                    JOptionPane.showMessageDialog(null, "OPPS!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "FALTAN DATOS POR INGRESAR!");
            }
            this.comboBoxCliente();
            mostrarMascotas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DATOS MAL DIGITADOS!");
        }
    }//GEN-LAST:event_btnCrearmascotaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (explorador.showDialog(null, "GUARDAR FACTURA") == JFileChooser.APPROVE_OPTION) {
            factura = explorador.getSelectedFile();

            if (factura.getName().endsWith("txt")) {

                var listaReportes = ccpago.infoFactura();
                System.out.println(listaReportes.size());
                String r = "";

                for (int i = 0; i < listaReportes.size(); i++) {
                    System.out.println(listaReportes.get(i));
                    r += listaReportes.get(i) + "\n";

                }
                System.out.println(r);
                String rta = a.GuardarArchivo(factura, r);

                if (rta != null) {
                    JOptionPane.showMessageDialog(null, rta);
                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }

            } else {
                JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed

        if (explorador.showDialog(null, "GUARDAR FACTURA") == JFileChooser.APPROVE_OPTION) {
            factura = explorador.getSelectedFile();

            if (factura.getName().endsWith("txt")) {
                String dia = String.valueOf(cbfechapago.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mes = String.valueOf(cbfechapago.getCalendar().get(Calendar.MONTH));
                String año = String.valueOf(cbfechapago.getCalendar().get(Calendar.YEAR));

                String fechaPago = dia + '/' + mes + '/' + año;

                String numeroCuotas = txtNumeroCuotas.getText();

                String idCliente = (cbidMascotapagos.getSelectedItem().toString());

                String idplan = cbidplanpagos.getSelectedItem().toString();

                String formato = "RECIBO GENERADO\n"
                + "FECHA :" + fechaPago + "\n"
                + "CUOTAS :" + numeroCuotas + "\n"
                + "INFO MASCOTA:\n" + idCliente + "\n"
                + "INFO PLAN :\n" + idplan + "\n";
                String rta = a.GuardarArchivo(factura, formato);

                if (rta != null) {
                    JOptionPane.showMessageDialog(null, rta);

                } else {
                    JOptionPane.showMessageDialog(null, "Error");
                }

            } else {
                JOptionPane.showMessageDialog(null, "ERROR DE FORMATO");
            }

        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnGenerarReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReciboActionPerformed
        try {
            if (validarDatosPago()) {

                String dia = String.valueOf(cbfechapago.getCalendar().get(Calendar.DAY_OF_MONTH));
                String mes = String.valueOf(cbfechapago.getCalendar().get(Calendar.MONTH));
                String año = String.valueOf(cbfechapago.getCalendar().get(Calendar.YEAR));
                String fechaPago = dia + '/' + mes + '/' + año;
                System.out.println(fechaPago);

                int numeroCuotas = Integer.parseInt(txtNumeroCuotas.getText());

                String idCliente = (cbidMascotapagos.getSelectedItem().toString());
                int primerEspacio = idCliente.indexOf(" ");

                int idFkCliente = Integer.parseInt(idCliente.substring(0, primerEspacio));

                String idplan = cbidplanpagos.getSelectedItem().toString();
                int pE = idplan.indexOf(" ");
                int idFkPlan = Integer.parseInt(idplan.substring(0, pE));

                Pago pago = new Pago(fechaPago, numeroCuotas, idFkCliente, idFkPlan);

                if (ccpago.crearPago(pago)) {
                    JOptionPane.showMessageDialog(this, "Pago generado");

                } else {
                    JOptionPane.showMessageDialog(this, "OPPS");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Llene los campos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en registro del pago");
        }

    }//GEN-LAST:event_btnGenerarReciboActionPerformed

    private void btnAgregarPLanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPLanActionPerformed

        try {
            if (validarDatosPlan()) {

                String codigop = txtCodigoplan.getText();
                int precio = Integer.parseInt(TxtPrecioPlan.getText());
                String nombrep = cbNamePlan.getSelectedItem().toString();

                Plan p = new Plan(codigop, nombrep, precio);

                if (ccplan.crearPlan(p)) {
                    JOptionPane.showMessageDialog(this, "Plan agredado");

                } else {
                    JOptionPane.showMessageDialog(this, "OPPS");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Llene los campos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en registro del plan");
        }
        mostrarPlanes();
    }//GEN-LAST:event_btnAgregarPLanActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        limpiarClientes();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void tbCLientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCLientesMouseClicked
        if (evt.getClickCount() == 1) {
            JTable recep = (JTable) evt.getSource();

            txtcc.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 0).toString());
            txtname.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 1).toString());
            txtlastname.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 2).toString());
            txtlocation.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 3).toString());
            txtphone.setText(recep.getModel().getValueAt(recep.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_tbCLientesMouseClicked

    private void btneliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarClienteActionPerformed

        int confirmacion = JOptionPane.showConfirmDialog(this, "Confirmas la eliminacion del usuario", null, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (confirmacion == 0) {
            String codigo = txtcc.getText();

            var rta = ccliente.borrarCliente(codigo);

            if (rta) {
                JOptionPane.showMessageDialog(this, "Clinete eliminado de la bd con exito !");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo borrar el registro !");
            }

            limpiarClientes();
            mostrarClientes();
        }
        this.mostrarClientes();
    }//GEN-LAST:event_btneliminarClienteActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        String cc = JOptionPane.showInputDialog(this, "Ingrese la CC");
        //instancio objeto
        String c = ccliente.buscarCliente(cc);
        if (c == null) {
            JOptionPane.showMessageDialog(this, "La cedula fue encontrado");
            limpiarClientes();

        } else {
            JOptionPane.showMessageDialog(this, c);

        }
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void BTNEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEDITARActionPerformed

        if (validarDatos()) {

            String identificacion = txtcc.getText();
            String nombres = txtname.getText();
            String apellido = txtlastname.getText();
            String direccion = txtlocation.getText();
            String telefono = txtphone.getText();

            Cliente c1 = new Cliente(identificacion, nombres, apellido, direccion, telefono);
            if (ccliente.editar(c1) == true) {
                JOptionPane.showMessageDialog(null, "EDITADO!");
            } else {
                JOptionPane.showMessageDialog(null, "OPPS!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "FALTAN DATOS POR INGRESAR!");
        }
        this.mostrarClientes();
    }//GEN-LAST:event_BTNEDITARActionPerformed

    private void txtAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarClienteActionPerformed

        if (validarDatos()) {

            String identificacion = txtcc.getText();
            String nombres = txtname.getText();
            String apellido = txtlastname.getText();
            String direccion = txtlocation.getText();
            String telefono = txtphone.getText();

            Cliente c1 = new Cliente(identificacion, nombres, apellido, direccion, telefono);
            if (ccliente.crearCliente(c1) == true) {
                JOptionPane.showMessageDialog(null, "AGREGADO!");
            } else {
                JOptionPane.showMessageDialog(null, "OPPS!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "FALTAN DATOS POR INGRESAR!");
        }
        this.mostrarClientes();
    }//GEN-LAST:event_txtAgregarClienteActionPerformed

    private void cbclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbclienteActionPerformed

    private void cbidMascotapagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbidMascotapagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbidMascotapagosActionPerformed

    //-----------------------validar camposs-------------------------------------------------------------------------
    public boolean validarDatos() {
        if (txtcc.getText().isEmpty() && txtname.getText().isEmpty() || txtlastname.getText().isEmpty() || txtlocation.getText().isEmpty() || txtphone.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public boolean validarDatosMascota() {
        if (txtCOD.getText().isEmpty() && txtmascotaname.getText().isEmpty() || txtfechanacimiento.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public boolean validarDatosPlan() {
        if (txtCodigoplan.getText().isEmpty() && TxtPrecioPlan.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public boolean validarDatosPago() {
        if (txtNumeroCuotas.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    //----------------------listados -----------------------------------------------------------------------------
    public void mostrarClientes() {
        while (modelCli.getRowCount() > 0) {
            modelCli.removeRow(0);
        }
        var lista = this.ccliente.listarClientes();
        for (Cliente cliente : lista) {
            Object[] cli = {cliente.getIdenctificacion(), cliente.getNombres(), cliente.getApellidos(), cliente.getDireccion(), cliente.getTelefono()};
            modelCli.addRow(cli);
        }

    }

    public void mostrarMascotas() {
        while (modelPet.getRowCount() > 0) {
            modelPet.removeRow(0);
        }
        var listam = this.ccmascota.listarMascotas();
        for (Mascota m : listam) {
//             String[] m = {"Codigo", "Mascota", "Fecha", "Peso", "Especie", "CLiente"};

            Object[] ma = {m.getIdPk(), m.getCodigo(), m.getNombre(), m.getAnnioNac(), m.getPeso(), m.getEspecie(), m.getNombreCliente()};
            modelPet.addRow(ma);

        }

    }

    public void mostrarPlanes() {
        while (modelplan.getRowCount() > 0) {
            modelplan.removeRow(0);
        }
        var listap = this.ccplan.listarPlanes();
        for (Plan p : listap) {
            Object[] plan = {p.getIdPk(), p.getCodigo(), p.getNombre(), p.getPrecio()};
            modelplan.addRow(plan);
        }

    }

    // -------------------limpiar datos-------------------------------------------------------------------------------------
    private void limpiarClientes() {
        txtcc.setText("");
        txtname.setText("");
        txtlastname.setText("");
        txtlocation.setText("");
        txtphone.setText("");
    }

    public void limpiarMasocta() {
        txtCOD.setText("");
        txtmascotaname.setText("");
        txtfechanacimiento.setText("");
        txtpeso.setText("");

    }

    //----------------------Combobox------------------------------------------------------------*----------------------
    public void comboBoxCliente() {
        cbcliente.removeAllItems();
        var listadoCliente = ccliente.listarClientes();

        for (int i = 0; i < listadoCliente.size(); i++) {
            String cli = listadoCliente.get(i).getIdPk() + " CC: " + listadoCliente.get(i).getIdenctificacion() + " Name: " + listadoCliente.get(i).getNombres().toUpperCase();
            cbcliente.addItem(cli);

        }

    }

    public void comboBoxMascota() {
        cbidMascotapagos.removeAllItems();
        var listadoMascotas = ccmascota.listarMascotas();
        for (int i = 0; i < listadoMascotas.size(); i++) {
            String cli = listadoMascotas.get(i).getIdPk() + " Codigo: " + listadoMascotas.get(i).getCodigo() + " Nombre: " + listadoMascotas.get(i).getNombre().toUpperCase();
            cbidMascotapagos.addItem(cli);

        }

    }

    public void comboBoxPlan() {
        cbidplanpagos.removeAllItems();
        var listadoPlanes = ccplan.listarPlanes();
        for (int i = 0; i < listadoPlanes.size(); i++) {
            String cli = listadoPlanes.get(i).getIdPk() + " Nombre Plan : " + listadoPlanes.get(i).getNombre().toUpperCase() + " VALOR: " + listadoPlanes.get(i).getPrecio();
            cbidplanpagos.addItem(cli);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNEDITAR;
    private javax.swing.JButton LimpiarPlan;
    private javax.swing.JTextField TxtPrecioPlan;
    private javax.swing.JButton btnAgregarPLan;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarPlan;
    private javax.swing.JButton btnCrearmascota;
    private javax.swing.JButton btnEditarPlan;
    private javax.swing.JButton btnEliminarPlan;
    private javax.swing.JButton btnGenerarRecibo;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultarmascota;
    private javax.swing.JButton btneliminarCliente;
    private javax.swing.JButton btneliminarmascota;
    private javax.swing.JButton btnmodificarmascota;
    private javax.swing.JComboBox<String> cbNamePlan;
    private javax.swing.JComboBox<String> cbcliente;
    private javax.swing.JComboBox<String> cbespecie;
    private com.toedter.calendar.JDateChooser cbfechapago;
    private javax.swing.JComboBox<String> cbidMascotapagos;
    private javax.swing.JComboBox<String> cbidplanpagos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbCLientes;
    private javax.swing.JTable tbPet;
    private javax.swing.JTable tbPlan;
    private javax.swing.JButton txtAgregarCliente;
    private javax.swing.JTextField txtCOD;
    private javax.swing.JTextField txtCodigoplan;
    private javax.swing.JTextField txtIDpkmascota;
    private javax.swing.JTextField txtNumeroCuotas;
    private javax.swing.JTextField txtcc;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtlocation;
    private javax.swing.JTextField txtmascotaname;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
